server:
  address: "127.0.0.1"
  port: 8080

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "secret-password"
  dbname: "postgres"
  cache:
    enable: true
    expirationTime: 1800000000000

linkGenerator:
  generatorType: "sequential"
  base: 64
  startingNumber: 10000000